## NumPy

**NumPy stands for Numerical Python. Generally NumPy comes whith the entire Anaconda Navigator Package but if you want to install it manually you can type the following code snippet in your Windows/Linux Terminal**

    pip install numpy
    conda install numpy
    

#### Setting the seed
Setting seed to any specific value can help to produce the same results everytime

Example: Ahead in the tutorial you will come across random function which produces random values everytime. Setting the seed to a specific value will help you to get the same value everytime on running the random function

In [ ]:
# Set seed for reproducibility
np.random.seed(seed=1234)

**NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).**

*    **Tensor**: collection of values 

<div align="left">
<img src="https://raw.githubusercontent.com/madewithml/images/master/basics/03_NumPy/tensors.png" width="650">
</div>

**NumPy Package is imported as following.**

In [ ]:
import numpy as np

In [ ]:
a = 6 #Single value assignment

In [ ]:
np.array(a) #Scalar (array)

array(6)

In [ ]:
a = [1,2,3] #List
a

In [ ]:
np.array(a) #Vector

array([1, 2, 3])

In [ ]:
b = [[1,2,3],[4,5,6],[7,8,9]] #2-Dimensional Matrix
b

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(b) #2-Dimensional Array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
x = [[[1,2],[3,4]],[[5,6],[7,8]]] #3-Dimensional Matrix

In [ ]:
np.array(x) #3-D Array / 3-Dimensional Tensor

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

**NumPy has certain built-in methods**

**arange**

Basically what arange does is, it forms an array of integers ranging from the starting point to the value right before the endpoint.
We can also specify the step.
  
    np.arange(start, stop, step)

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

**zeros and ones**
It forms an array of zeros and ones.

    np.zeros(number of 0s to be present in the array)
    np.ones(same as above)
    np.zeros(passing a tuple (3,3))
it will form a matrix of dimensions 3*3
    
    p.ones(same as above)

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

**linspace**

**Return evenly spaced numbers over a specified interval.**

    numpy.linspace(start, stop, step)

In [ ]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [ ]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

**eye**

**Returns an identity matrix**

    numpy.eye(dimensions)

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

**Random**

NumPy can create randon number arrays

**rand**

create an array of random samples from a uniform range of [0,1)

In [ ]:
np.random.rand(2)

array([0.29130709, 0.90836832])

In [ ]:
np.random.rand(5,5)

array([[0.72280638, 0.09924553, 0.78978599, 0.05723986, 0.02339967],
       [0.77601024, 0.59157846, 0.97318219, 0.31216264, 0.42440455],
       [0.05362013, 0.00580705, 0.17127338, 0.94088887, 0.6253173 ],
       [0.7860941 , 0.97527041, 0.07861808, 0.25420798, 0.10971163],
       [0.35947818, 0.89613527, 0.29904265, 0.95698348, 0.22522896]])

**randn**

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [ ]:
np.random.randn(2)

array([0.41518126, 1.06147693])

In [ ]:
np.random.randn(5,5)

array([[-1.13455682, -0.32243936, -0.0865739 ,  1.26049114,  0.67321413],
       [-0.11236745,  0.1502616 ,  0.31021566,  2.53034894,  2.15801691],
       [ 0.78914273, -1.56689017,  0.2555069 , -0.32107163, -0.49892397],
       [ 0.10349395, -0.08546306, -0.87911568,  0.42777504,  0.35935935],
       [ 0.79037724, -0.86313219,  0.9656345 ,  1.59707222, -0.87861609]])

**randint**

Return random integers from low(inclusive) to high(exclusive)

In [ ]:
np.random.randint(1,100)

24

In [ ]:
np.random.randint(1,100,10)

array([ 2, 14, 87, 56, 12, 22, 27, 80, 65, 63])

**Attributes and Methods**

1. Reshape
<div align="left">
<img src="https://raw.githubusercontent.com/madewithml/images/master/basics/03_NumPy/reshape.png" width="450">
</div>
2. max, min, argmax, argmin
3. Shape
4. dtype
5. Transpose
<div align="left">
<img src="https://raw.githubusercontent.com/madewithml/images/master/basics/03_NumPy/transpose.png" width="400">
</div>

In [ ]:
#initializing the arrays
arr = np.arange(25) 
ranarr = np.random.randint(0,50,10)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
arr.reshape(5,5) #Reshaping to 5x5 Dimension (Matrix)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
ranarr

array([22, 44, 11, 16, 12, 12, 15,  9,  1, 37])

In [ ]:
ranarr.max() #Finding the maximum value from the 'ranarr' array

44

In [ ]:
#Finding the index value of the maximum value from the array
ranarr.argmax() 

1

In [ ]:
#Finding the minimum value of the array
ranarr.min()

1

In [ ]:
#Finding the index value of the minimum value from the array
ranarr.argmin()

8

In [ ]:
#A function that returns the shape of the array.
arr.shape

(25,)

In [ ]:
#A Function to returns the type of the array.
arr.dtype

dtype('int64')

In [ ]:
# Transposing
x = np.array([[1,2,3], [4,5,6]])
print ("x:\n", x)
print ("x.shape: ", x.shape)
y = np.transpose(x, (1,0)) # flip dimensions at index 0 and 1
print ("y:\n", y)
print ("y.shape: ", y.shape)

x:
 [[1 2 3]
 [4 5 6]]
x.shape:  (2, 3)
y:
 [[1 4]
 [2 5]
 [3 6]]
y.shape:  (3, 2)


### Additional references on Unintended Reshaping

Though reshaping is very convenient to manipulate tensors, we must be careful of their pitfalls as well. Let's look at the example below. Suppose we have `x`, which has the shape `[2 X 3 X 4]`. 
```
[[[ 1  1  1  1]
  [ 2  2  2  2]
  [ 3  3  3  3]]
 [[10 10 10 10]
  [20 20 20 20]
  [30 30 30 30]]]
```
We want to reshape x so that it has shape `[3 X 8]` which we'll get by moving the dimension at index 0 to become the dimension at index 1 and then combining the last two dimensions. But when we do this, we want our output 

to look like:
✅
```
[[ 1  1  1  1 10 10 10 10]
 [ 2  2  2  2 20 20 20 20]
 [ 3  3  3  3 30 30 30 30]]
```
and not like:
❌
```
[[ 1  1  1  1  2  2  2  2]
 [ 3  3  3  3 10 10 10 10]
 [20 20 20 20 30 30 30 30]]
 ```
even though they both have the same shape `[3X8]`.

In [ ]:
x = np.array([[[1, 1, 1, 1], [2, 2, 2, 2], [3, 3, 3, 3]],
              [[10, 10, 10, 10], [20, 20, 20, 20], [30, 30, 30, 30]]])
print ("x:\n", x)
print ("x.shape: ", x.shape)

x:
 [[[ 1  1  1  1]
  [ 2  2  2  2]
  [ 3  3  3  3]]

 [[10 10 10 10]
  [20 20 20 20]
  [30 30 30 30]]]
x.shape:  (2, 3, 4)


When we naively do a reshape, we get the right shape but the values are not what we're looking for.
<div align="left">
<img src="https://raw.githubusercontent.com/madewithml/images/master/basics/03_NumPy/reshape_wrong.png" width="600">
</div>

In [ ]:
# Unintended reshaping
z_incorrect = np.reshape(x, (x.shape[1], -1))
print ("z_incorrect:\n", z_incorrect)
print ("z_incorrect.shape: ", z_incorrect.shape)

z_incorrect:
 [[ 1  1  1  1  2  2  2  2]
 [ 3  3  3  3 10 10 10 10]
 [20 20 20 20 30 30 30 30]]
z_incorrect.shape:  (3, 8)


Instead, if we transpose the tensor and then do a reshape, we get our desired tensor. Transpose allows us to put our two vectors that we want to combine together and then we use reshape to join them together.
Always create a dummy example like this when you’re unsure about reshaping. Blindly going by the tensor shape can lead to lots of issues downstream.
<div align="left">
<img src="https://raw.githubusercontent.com/madewithml/images/master/basics/03_NumPy/reshape_right.png" width="600">
</div>

In [ ]:
# Intended reshaping
y = np.transpose(x, (1,0,2))
print ("y:\n", y)
print ("y.shape: ", y.shape)
z_correct = np.reshape(y, (y.shape[0], -1))
print ("z_correct:\n", z_correct)
print ("z_correct.shape: ", z_correct.shape)

y:
 [[[ 1  1  1  1]
  [10 10 10 10]]

 [[ 2  2  2  2]
  [20 20 20 20]]

 [[ 3  3  3  3]
  [30 30 30 30]]]
y.shape:  (3, 2, 4)
z_correct:
 [[ 1  1  1  1 10 10 10 10]
 [ 2  2  2  2 20 20 20 20]
 [ 3  3  3  3 30 30 30 30]]
z_correct.shape:  (3, 8)


**NumPy Operation**

1. Arithmetic
  1. addition
  2. subtraction
  3. multiplication
  4. division
  5. exponentiation
  

The following cells works on vectors. The arithmetic operations are performed with respect to their indexes.

In [ ]:
arr = np.arange(0,10)

In [ ]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
print(arr + arr) #normal addition
print(np.add(arr,arr)) #using the function of NumPy

[ 0  2  4  6  8 10 12 14 16 18]
[ 0  2  4  6  8 10 12 14 16 18]


In [ ]:
print(arr * arr) #normal multiplication
print(np.multiply(arr,arr)) #using the function of NumPy

[ 0  1  4  9 16 25 36 49 64 81]
[ 0  1  4  9 16 25 36 49 64 81]


In [ ]:
print(arr-arr) #normal substraction
print(np.subtract(arr,arr)) #using the function of NumPy

[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]


In [ ]:
print(arr/arr)

[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [ ]:
print(1/arr)

[       inf 1.         0.5        0.33333333 0.25       0.2
 0.16666667 0.14285714 0.125      0.11111111]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


In [ ]:
print(arr**3) #exponentiation (raise to)

[  0   1   8  27  64 125 216 343 512 729]


2. Universal array functions
  
  1. sqrt()
  2. exp() (e^)
  3. max()
  4. sin()
  5. log()

In [ ]:
#Taking Square Roots
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [ ]:
#Calcualting exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [ ]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [ ]:
np.max(arr) #same as arr.max()

9

###Dot product
One of the most common NumPy operations we’ll use in machine learning is matrix multiplication using the dot product. We take the rows of our first matrix (2) and the columns of our second matrix (2) to determine the dot product, giving us an output of `[2 X 2]`. The only requirement is that the inside dimensions match, in this case the first matrix has 3 columns and the second matrix has 3 rows. 

<div align="left">
<img src="https://raw.githubusercontent.com/madewithml/images/master/basics/03_NumPy/dot.gif" width="450">
</div>

In [ ]:
# Dot product
a = np.array([[1,2,3], [4,5,6]], dtype=np.float64) # we can specify dtype
b = np.array([[7,8], [9,10], [11, 12]], dtype=np.float64)
c = a.dot(b)
print (f"{a.shape} · {b.shape} = {c.shape}")
print (c)

(2, 3) · (3, 2) = (2, 2)
[[ 58.  64.]
 [139. 154.]]


###Operation with respect to the axis
We can also do operations across a specific axis.

<div align="left">
<img src="https://raw.githubusercontent.com/madewithml/images/master/basics/03_NumPy/axis.gif" width="450">
</div>

In [ ]:
# Sum across a dimension
x = np.array([[1,2],[3,4]])
print (x)
print ("sum all: ", np.sum(x)) # adds all elements
print ("sum axis=0: ", np.sum(x, axis=0)) # sum across rows
print ("sum axis=1: ", np.sum(x, axis=1)) # sum across columns

[[1 2]
 [3 4]]
sum all:  10
sum axis=0:  [4 6]
sum axis=1:  [3 7]


In [ ]:
# Min/max
x = np.array([[1,2,3], [4,5,6]])
print ("min: ", x.min())
print ("max: ", x.max())
print ("min axis=0: ", x.min(axis=0))
print ("min axis=1: ", x.min(axis=1))

min:  1
max:  6
min axis=0:  [1 2 3]
min axis=1:  [1 4]


**So basically till now we have seen how to create arrays, either manually or randomly. We have also seen how different operations can be performed on the array. But what if, we want to work on selective portion of the array. NumPy provides indexing and selection techniques too.**

**Indexing and Selection**


<div align="left">
<img src="https://raw.githubusercontent.com/madewithml/images/master/basics/03_NumPy/indexing.png" width="300">
</div>

In [ ]:
a = np.arange(0,11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#Get a value at an index
a[8]

8

In [ ]:
#Get values in a range (Slicing)
a[1:5]

array([1, 2, 3, 4])

**Few examples for indexing and slicing**


In [ ]:
# Indexing
x = np.array([1, 2, 3])
print ("x: ", x)
print ("x[0]: ", x[0])
x[0] = 0
print ("x: ", x)

x:  [1 2 3]
x[0]:  1
x:  [0 2 3]


In [ ]:
# Slicing
x = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print (x)
print ("x column 1: ", x[:, 1]) 
print ("x row 0: ", x[0, :]) 
print ("x rows 0,1 & cols 1,2: \n", x[0:2, 1:3]) 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
x column 1:  [ 2  6 10]
x row 0:  [1 2 3 4]
x rows 0,1 & cols 1,2: 
 [[2 3]
 [6 7]]


**List doesnot have the ability to assign a group of elements the same value at the same time. But NumPy provides this ability by the concept:**

**Broadcasting**

<div align="left">
<img src="https://raw.githubusercontent.com/madewithml/images/master/basics/03_NumPy/broadcasting.png" width="300">
</div>


In [ ]:
#Setting a value with index range (Broadcasting)
a[0:5]=100

#Show
a

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [ ]:
# Reset array, we'll see why I had to reset in  a moment
a = np.arange(0,11)

#Show
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#Important notes on Slices
slice_of_a = arr[0:6]

#Show slice
slice_of_a

array([0, 1, 2, 3, 4, 5])

In [ ]:
#Change Slice
slice_of_a[:]=99

#Show Slice again
slice_of_a

#The code snippet will change the entire array when the starting and stopping positions are not specified

array([99, 99, 99, 99, 99, 99])

In [ ]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
#Indexing row
arr_2d[1]


array([20, 25, 30])

In [ ]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [ ]:
# Getting individual element value
arr_2d[1,0]

20

In [ ]:
# 2D array slicing
#arr[row_start:row_end,col_start:col_end]
#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [ ]:
#Shape bottom row 
arr_2d[2,:]

array([35, 40, 45])

In [ ]:
# An example showing the working of broadcasting on the arithmetic operation
x = np.array([1,2]) # vector
y = np.array(3) # scalar
z = x + y
print ("z:\n", z)

z:
 [4 5]


**Going through Selection for comparison based operation**

In [ ]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
print(arr > 4 ) #boolean indexing for vectors

[False False False False  True  True  True  True  True  True]


In [ ]:
bool_arr = arr>4

In [ ]:
print(bool_arr) #boolean indexing for vectors 

[False False False False  True  True  True  True  True  True]


In [ ]:
arr[bool_arr] #indexing

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
arr[arr>2] 
#indexing to provide only the values that satifies the conditon

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Boolean array indexing for 2-D
x = np.array([[1, 2], [3, 4], [5, 6]])
print ("x:\n", x)
print ("x > 2:\n", x > 2)
print ("x[x > 2]:\n", x[x > 2])

x:
 [[1 2]
 [3 4]
 [5 6]]
x > 2:
 [[False False]
 [ True  True]
 [ True  True]]
x[x > 2]:
 [3 4 5 6]


**This tutorial is intended to be a public resource. As such, if you see any glaring inaccuracies or if a critical topic is missing, please feel free to point it out or (preferably) submit a pull request to improve the tutorial. Also, we are always looking to improve the scope of this article. For anything feel free to mail us @ colearninglounge@gmail.com**

The author of this article is Shalin Shah. You can follow him on 
<div align="left">
<a href="https://www.linkedin.com/in/shalin-shah-329ba016a/">LinkedIn,</a> <a href="https://github.com/shalinshah12"> GitHub, and,</a><a href="https://twitter.com/shalinrshah12"> Twitter</a>
</div>